version: 2.1
executors:
  node-executor:
    docker:
      - image: cimg/node:18.4.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          PROJECT_NAME: circleci-poc

# Define the jobs we want to run for this project
jobs:
  build:
    executor: node-executor
    steps:
      - setup_remote_docker
      - checkout
      - run: echo "This is the build job"
      - run: docker build . -t $DOCKERHUB_USERNAME/$PROJECT_NAME:$CIRCLE_SHA1 -t $DOCKERHUB_USERNAME/$PROJECT_NAME:$ENVIRONMENT
      - run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: docker push --all-tags $DOCKERHUB_USERNAME/$PROJECT_NAME
  test:
    executor: node-executor
    steps:
      - checkout
      - run: echo "this is the test job"
      - run: npm install
      - run: npm test
  test-e2e:
    executor: node-executor
    steps:
      - checkout
      - run: echo "this is the test job"
      - run: npm install
      - run: npm run test:e2e
  deploy:
    executor: node-executor
    steps:
      - setup_remote_docker
      - run: docker pull $DOCKERHUB_USERNAME/$PROJECT_NAME:$CIRCLE_SHA1
      - run: echo "deploying in a imaginary place"


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test:
          context:
            - org-basic-context
      - test-e2e:
          context:
            - org-basic-context
      - build:
          context:
            - org-basic-context
          requires:
            - test
            - test-e2e
          filters:
            branches:
              only:
                - master
      - request_deployment:
          type: approval
          requires:
          - build
      - deploy:
          context:
            - org-basic-context
          requires:
            - request_deployment
